services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network

volumes:
  ollama_data:

networks:
  app-network:
    driver: bridge
